version: "2"

networks:
    app_network:
        driver: bridge

services:

    zookeeper:
        image: wurstmeister/zookeeper
        container_name: zookeeper
        hostname: zookeeper
        networks:
            - app_network
        ports:
            - '2181:2181'
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
    
    kafka:
        image: wurstmeister/kafka
        container_name: kafka
        hostname: kafka
        networks:
            - app_network
        ports:
            - '9092:9092'
        depends_on:
            - zookeeper
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=kafka
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_LOG_RETENTION_HOURS=1
            - KAFKA_MESSAGE_MAX_BYTES=2000000000
            - KAFKA_CREATE_TOPICS=query1:1:1

    jobmanager:
        image: flink
        hostname: jobmanager
        container_name: jobmanager
        expose:
            - "6123"
        networks:
            - app_network
        ports:
            - "8081:8081"
        command: jobmanager
        environment:
            - JOB_MANAGER_RPC_ADDRESS=jobmanager
        volumes:
            - ./flink_jar:/sabd/jar
            - ./result:/sabd/result

    taskmanager:
        image: flink
        hostname: taskmanager1
        container_name: taskmanager1
        networks:
            - app_network
        expose:
            - "6121"
            - "6122"
        depends_on:
            - jobmanager
        command: taskmanager
        environment:
            - JOB_MANAGER_RPC_ADDRESS=jobmanager
        volumes:
            - ./result:/sabd/result




    kafka-producer:
        image: wurstmeister/kafka
        container_name: kafka-producer
        hostname: kafka-producer
        networks:
            - app_network
        depends_on:
            - zookeeper
            - kafka
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=kafka
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_LOG_RETENTION_HOURS=1
            - KAFKA_MESSAGE_MAX_BYTES=2000000000
        entrypoint: /bin/sh
        stdin_open: true
        tty: true
        volumes:
            - ./dataset:/sabd/dataset

  